### ISSUE TITLE
bug: error building ISO639-3 data

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/api.keyman.com#143]
```
[02/25/2021 20:58:27 > fc5cb9: INFO] Running D:\home\site\wwwroot/.data/iso639-3.sql
[02/25/2021 20:58:30 > fc5cb9: INFO] Array
[02/25/2021 20:58:30 > fc5cb9: INFO] (
[02/25/2021 20:58:30 > fc5cb9: INFO]     [0] => 21S01
[02/25/2021 20:58:30 > fc5cb9: INFO]     [1] => 110
[02/25/2021 20:58:30 > fc5cb9: INFO]     [2] => [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There are fewer columns in the INSERT statement than values specified in the VALUES clause. The number of values in the VALUES clause must match the number of columns specified in the INSERT statement.
[02/25/2021 20:58:30 > fc5cb9: INFO] )
[02/25/2021 20:58:30 > fc5cb9: INFO] Failure: PDOException: SQLSTATE[21S01]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There are fewer columns in the INSERT statement than values specified in the VALUES clause. The number of values in the VALUES clause must match the number of columns specified in the INSERT statement. in D:\home\site\wwwroot\tools\db\build\build.inc.php:148
[02/25/2021 20:58:30 > fc5cb9: INFO] Stack trace:
[02/25/2021 20:58:30 > fc5cb9: INFO] #0 D:\home\site\wwwroot\tools\db\build\build.inc.php(148): PDO->exec()
[02/25/2021 20:58:30 > fc5cb9: INFO] #1 D:\home\site\wwwroot\tools\db\build\build.inc.php(67): BuildDatabaseClass->sqlrun()
[02/25/2021 20:58:30 > fc5cb9: INFO] #2 D:\home\site\wwwroot\tools\db\build\build_cli.php(30): BuildDatabaseClass->BuildDatabase()
[02/25/2021 20:58:30 > fc5cb9: INFO] #3 {main}
[02/25/2021 20:58:30 > fc5cb9: INFO] 
```

There are fewer columns in the INSERT statement than values specified in the VALUES clause. The number of values in the VALUES clause must match the number of columns specified in the INSERT statement.

This suggests the format of the ISO639-3 data has changed.

This error is preventing the build from completing.

**Comment by mcdurdin** [comment]
There is a single row in the iso639-3.tab file which has an extra tabstop, causing this problem:

```sql
INSERT k0.t_iso639_3 (Id,Part2B,Part2T,Part1,_Scope,_Type,Ref_Name,_Comment) VALUES(N'vka',N'',N'',N'',N'I',N'E',N'Kariyarra',N'',N'')
```

A workaround could be to use the field name column count for all rows and ignore (perhaps with a log warning) subsequent columns.

I have notified the registrar of the data so they can fix the source data but unknown how long it will take to resolve from their end.
